Models/Movie.cs
using ETickets.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ETickets.Models
{
    public class Movie : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get;set; }
        public DateTime EndDate { get; set; }
        public DateTime ReleaseDate { get; set; }
        public double Price { get; set; }
        public string ImageUrl { get; set; }
        public MovieCategory MovieCategory { get; set; }
        public List<MovieActors> MovieActors { get; set; }
        public int CinemaId {  get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema {  get; set; }
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }

    }
}

Controllers/ActorController.cs
using ETickets.Data;
using ETickets.Data.DTOs;
using ETickets.Data.Services;
using ETickets.Data.Static;
using ETickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ETickets.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorServices _services;
        public ActorController(IActorServices services)
        {
            _services = services;
        }
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Index()
        {
            var data = await _services.GetAllAsync();
            return View(data);
        }
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Create(ActorDto actorDto)
        {
            if (!ModelState.IsValid)
            {
                return View(actorDto);
            }
            var actor = new Actor()
            {
                ProfilePictureUrl = actorDto.ProfilePictureUrl,
                FullName = actorDto.FullName,
                Bio = actorDto.Bio
            };
            _services.AddAsync(actor);

            return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var actor = await _services.GetByIdAsync(id);
            if(actor == null)
            {
                return View("NotFound");
            }
            return View(actor);
            
        }
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit(int id)
        {
            var actor = await _services.GetByIdAsync(id);
            if (actor == null)
            {
                return View("NotFound");
            }
            return View(actor);
        }
        [HttpPost]
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit([FromRoute] int id,ActorDto actorDto)
        {
            if (!ModelState.IsValid)
                return View(actorDto);
            var actor = await _services.GetByIdAsync(id);
            if (actor == null)
            {
                return View("NotFound");
            }

            actor.FullName = actorDto.FullName;
            actor.ProfilePictureUrl = actorDto.ProfilePictureUrl;
            actor.Bio = actorDto.Bio;
           
            await _services.UpdateAsync(actor);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Delete(int id)
        {
            var actor = await _services.GetByIdAsync(id);
            if (actor == null)
            {
                return View("NotFound");
            }
            
            await _services.DeleteAsync(actor);
            return Json(new { success = true });
        }
    }
}

Controllers/MovieController.cs
using ETickets.Data;
using ETickets.Data.Services;
using ETickets.Data.Static;
using ETickets.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ETickets.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMoviesService _service;
        public MovieController(IMoviesService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index(MovieCategory? category)
        {
            var movies = await _service.GetAllAsync(m=>m.Cinema);
            if (category.HasValue)
            {
                ViewBag.SelectedCategory = category;
                movies = movies.Where(m => m.MovieCategory == category).ToList();
            }
            else
            {
                ViewBag.SelectedCategory = null;
            }
            return View("Index", movies);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var movie=await _service.GetMovieByIdAsync(id);
            if (movie == null)
            {
                return View("NotFound");
            }
            return View(movie);
        }
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Create()
        {
            var movieDropDownValue = await _service.GetMovieDropDownsValues();
            ViewBag.Cinemas = new SelectList(movieDropDownValue.Cinemas,  "Id", "Name" );
            ViewBag.Producers = new SelectList(movieDropDownValue.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownValue.Actors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Create(MovieVM movieVM)
        {
            if (!ModelState.IsValid)
            {
                var movieDropDownValue = await _service.GetMovieDropDownsValues();
                ViewBag.Cinemas = new SelectList(movieDropDownValue.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownValue.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownValue.Actors, "Id", "FullName");
            }
            await _service.AddMovieAsync(movieVM);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit(int id)
        {
            var movie = await _service.GetMovieByIdAsync(id);
            if (movie == null)
                return View("NotFound");
            var response = new MovieVM()
            {
                ID = movie.Id,
                Title = movie.Title,
                Description = movie.Description,
                Price = movie.Price,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                ImageURL = movie.ImageUrl,
                CinemaID = movie.CinemaId,
                ProdcerID = movie.ProducerId,
                MovieCategory = movie.MovieCategory,
                ReleaseDate = movie.ReleaseDate,
                ActorIDs = movie.MovieActors.Select(n => n.ActorId).ToList(),
            };
            var movieDropDownValue = await _service.GetMovieDropDownsValues();
            ViewBag.Cinemas = new SelectList(movieDropDownValue.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownValue.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownValue.Actors, "Id", "FullName");
            return View(response);
        }
        [HttpPost]
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit(int id,MovieVM movieVM)
        {
            if (id!=movieVM.ID)
                return View("NotFound");
            if (!ModelState.IsValid)
            {
                var movieDropDownValue = await _service.GetMovieDropDownsValues();
                ViewBag.Cinemas = new SelectList(movieDropDownValue.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownValue.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownValue.Actors, "Id", "FullName");
                return View(movieVM);
            }
            await _service.UpdateMovieAsync(movieVM);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchTerm)
        {
            var movies = await _service.GetAllAsync(m => m.Cinema);

            if (!string.IsNullOrEmpty(searchTerm))
            {
                ViewData["SearchTerm"] = searchTerm;
                searchTerm = searchTerm.Trim().ToLower();
                movies = movies.Where(m =>
                    m.Title.ToLower().Contains(searchTerm) ||
                    m.Description.ToLower().Contains(searchTerm) ||
                    m.MovieCategory.ToString().ToLower().Contains(searchTerm)
                ).ToList();
            }
            return View("Filter", movies);
        }

    }
}

Controllers/OrdersController.cs
using ETickets.Data.Cart;
using ETickets.Data.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ETickets.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly IOrderService _orderService;
        private readonly ShoppingCart _shoppingCart;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _orderService.GetOrdersByUserIDAndRoleAsync(userID, userRole);

            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
                ShoppingCartAmount=_shoppingCart.GetShoppingCartTotalAmount()
            };
            return View(response);
        }


        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }


        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAdress = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userID, userEmailAdress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

Views/Movie/Create.cshtml
@model MovieVM
@{
    ViewData["Title"] = "أضافه فيلم جديد";
    Layout = "_SecLayout";
}

<div class="row text align-content-center justify-content-center">
    <div class="col-md-10 ltor">
        <h4 class="section-title">أضافه فيلم جديد</h4>

        <div class="row justify-content-center">
            <div class="col-md-10">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <!-- Preview Image -->
                    <div class="form-group imagepre">
                        <img id="PosterPreview" class="imagepic" />
                    </div>

                    <div class="form-group">
                        <label asp-for="ImageURL" class="control-label">رابط الصورة</label>
                        <input asp-for="ImageURL" class="form-control" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Title" class="control-label">عنوان الفيلم</label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description" class="control-label">الوصف</label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Price" class="control-label">السعر</label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label">تاريخ البداية</label>
                        <input asp-for="StartDate" class="form-control" type="date" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label">تاريخ الانتهاء</label>
                        <input asp-for="EndDate" class="form-control" type="date" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ReleaseDate" class="control-label">تاريخ العرض</label>
                        <input asp-for="ReleaseDate" class="form-control" type="date" />
                        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="MovieCategory" class="control-label">التصنيف</label>
                        <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                        <span asp-validation-for="MovieCategory" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CinemaID" class="control-label">دور السينما</label>
                        <select asp-for="CinemaID" class="form-control" asp-items="ViewBag.Cinemas"></select>
                        <span asp-validation-for="CinemaID" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProdcerID" class="control-label">المنتج</label>
                        <select asp-for="ProdcerID" class="form-control" asp-items="ViewBag.Producers"></select>
                        <span asp-validation-for="ProdcerID" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ActorIDs" class="control-label">الممثلين</label>
                        <select asp-for="ActorIDs" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                        <span asp-validation-for="ActorIDs" class="text-danger"></span>
                    </div>

                    <div class="form-group pt-3">
                        <input type="submit" value="أضف الفيلم" class="btn btn-success float-right" />
                        <a class="btn btn-primary" asp-action="Index">عرض الكل</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var preview = document.getElementById('PosterPreview');
            preview.src = $("#ImageURL").val();
        });

        $("#ImageURL").on("change", function () {
            var preview = document.getElementById('PosterPreview');
            preview.src = $(this).val();
        });
    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Movie/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Movie Details";
    Layout = "_SecLayout";
}

<div class="movie-details">
    <img src="@Model.ImageUrl" alt="@Model.Title" />

    <div class="movie-info2">
        <h2>@Model.Title</h2>

        <p>@Model.Description</p>

        <div class="meta">
            <p><strong>Category:</strong> @Model.MovieCategory</p>
            <p><strong>Price:</strong> $@Model.Price</p>
            <p><strong>Start Date:</strong> @Model.StartDate.ToString("dd MMM yyyy")</p>
            <p><strong>End Date:</strong> @Model.EndDate.ToString("dd MMM yyyy")</p>
            <p><strong>Release Date:</strong> @Model.ReleaseDate.ToString("dd MMM yyyy")</p>
            <p><strong>Cinema:</strong> @Model.Cinema.Name</p>
            <p><strong>Producer:</strong> @Model.Producer.FullName</p>
        </div>

        <div>
            <strong>Actors:</strong>
            <ul>
                @foreach (var actor in Model.MovieActors)
                {
                    <a asp-action="Details" asp-controller="Actor" asp-route-id="@actor.ActorId" >
                    <li><img src="@actor.Actor.ProfilePictureUrl" alt="@actor.Actor.FullName" /></li>
                    </a>
                }
            </ul>
        </div>

        <div class="movie-buttons">
            <a class="btn btn-primary" asp-controller="Orders"
               asp-action="AddItemToShoppingCart"
               asp-route-id="@Model.Id">Add to Cart</a>
            <a class="btn btn-secondary" asp-controller="Orders"
               asp-action="AddItemToShoppingCart"
               asp-route-id="@Model.Id">Order Now</a>
        </div>
    </div>
</div>

Views/Movie/Edit.cshtml
@model MovieVM
@{
    ViewData["Title"] = "تعديل بيانات الفيلم";
    Layout = "_SecLayout";
}

<div class="row text align-content-center justify-content-center">
    <div class="col-md-10 ltor">
        <h4 class="section-title">تعديل بيانات الفيلم</h4>

        <div class="row justify-content-center">
            <div class="col-md-10">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <!-- Hidden ID -->
                    <input type="hidden" asp-for="ID" />

                    <!-- Preview Image -->
                    <div class="form-group imagepre">
                        <img id="PosterPreview" class="imagepic" />
                    </div>

                    <div class="form-group">
                        <label asp-for="ImageURL" class="control-label">رابط الصورة</label>
                        <input asp-for="ImageURL" class="form-control" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Title" class="control-label">عنوان الفيلم</label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description" class="control-label">الوصف</label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Price" class="control-label">السعر</label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label">تاريخ البداية</label>
                        <input asp-for="StartDate" class="form-control" type="date" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label">تاريخ الانتهاء</label>
                        <input asp-for="EndDate" class="form-control" type="date" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ReleaseDate" class="control-label">تاريخ العرض</label>
                        <input asp-for="ReleaseDate" class="form-control" type="date" />
                        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="MovieCategory" class="control-label">التصنيف</label>
                        <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                        <span asp-validation-for="MovieCategory" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CinemaID" class="control-label">دور السينما</label>
                        <select asp-for="CinemaID" class="form-control" asp-items="ViewBag.Cinemas"></select>
                        <span asp-validation-for="CinemaID" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProdcerID" class="control-label">المنتج</label>
                        <select asp-for="ProdcerID" class="form-control" asp-items="ViewBag.Producers"></select>
                        <span asp-validation-for="ProdcerID" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ActorIDs" class="control-label">الممثلين</label>
                        <select asp-for="ActorIDs" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                        <span asp-validation-for="ActorIDs" class="text-danger"></span>
                    </div>

                    <div class="form-group pt-3">
                        <input type="submit" value="تحديث الفيلم" class="btn btn-warning float-right" />
                        <a class="btn btn-primary" asp-action="Index">عرض الكل</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var preview = document.getElementById('PosterPreview');
            preview.src = $("#ImageURL").val();
        });

        $("#ImageURL").on("change", function () {
            var preview = document.getElementById('PosterPreview');
            preview.src = $(this).val();
        });
    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Movie/Filter.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "All Movies";
    Layout = "_SecLayout";
}


@* @await Html.PartialAsync("_CreateItem", "Movie") *@
<div class="section">
    <p>
        <h2 class="section-title"> نتائج البحث عن @ViewData["searchTerm"]</h2>
    </p>
</div>
<div class="movies-grid">
    @foreach (var item in Model)
    {
        <div class="movie-card card-clickable" data-href="@Url.Action("Details", new { id = item.Id })">
            <img src="@item.ImageUrl" alt="@item.Title" class="movie-poster" />
            <a class="text-white float-left Edit-Icon" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
            @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
            {
                <div class="badge badge-success badge-hov">متوفر</div>
            }
            else if (DateTime.Now > item.EndDate)
            {
                <div class="badge badge-danger badge-hov">منتهي</div>
            }
            else
            {
                <div class="badge badge-primary badge-hov">قريبًا</div>
            }

            <div class="movie-info">
                <h3 class="movie-title">@item.Title</h3>
                <div class="movie-meta">
                    <span class="d-block">@item.Cinema.Name</span>
                </div>
                <div class="movie-meta">

                    <span>@item.ReleaseDate.Year</span>
                </div>

            </div>

            <div class="movie-card-overlay">
                <div class="overlay-buttons">
                    <a class="overlay-btn" title="Details" asp-action="Details" asp-route-id="@item.Id">▶️</a>
                    <a class="overlay-btn"
                       title="Add to Cart">➕</a>
                    <button class="overlay-btn" title="Like">❤️</button>
                </div>
                <div>
                    <a class="btn btn-success text-white @(DateTime.Now > item.EndDate ? "disabled" : "")"
                       style="width:100%; font-size:10px;"
                       asp-controller="Orders"
                       asp-action="AddItemToShoppingCart"
                       asp-route-id="@item.Id">
                        <i class="bi bi-cart-plus"></i> @item.Price.ToString("c")
                    </a>
                </div>
            </div>
        </div>
    }
</div>


<script>
    document.querySelectorAll('.card-clickable').forEach(card => {
        card.style.cursor = 'pointer';
        card.addEventListener('click', function (e) {
            // لو المستخدم ضغط على زرار أو لينك جوا الكارد، ما يروحش لصفحة التفاصيل
            if (!e.target.closest('a') && !e.target.closest('button')&&!e.target.closest('span')) {
                window.location.href = card.getAttribute('data-href');
            }
        });
    });
</script>

Views/Movie/Index.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Now Streaming";
    Layout = "_MyLayout";
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
@await Html.PartialAsync("_CreateItem", "Movie")
}
    <div class="movies-grid">
        @foreach (var item in Model)
        {
        <div class="movie-card card-clickable" data-href="@Url.Action("Details", new { id = item.Id })">
                <img src="@item.ImageUrl" alt="@item.Title" class="movie-poster" />
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <a class="text-white float-left Edit-Icon" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
            }
                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                {
                    <div class="badge badge-success badge-hov">متوفر</div>
                }
                else if (DateTime.Now > item.EndDate)
                {
                    <div class="badge badge-danger badge-hov">منتهي</div>
                }
                else
                {
                    <div class="badge badge-primary badge-hov">قريبًا</div>
                }

                <div class="movie-info">
                    <h3 class="movie-title">@item.Title</h3>
                <div class="movie-meta">
                <span class="d-block">@item.Cinema.Name</span>
                </div>
                    <div class="movie-meta">
                    
                    <span >@item.ReleaseDate.Year</span>
                    </div>
                    
                </div>

                <div class="movie-card-overlay">
                    <div class="overlay-buttons">
                    <a class="overlay-btn" title="Details" asp-action="Details" asp-route-id="@item.Id">▶️</a>
                        <a class="overlay-btn"
                       asp-controller="Orders" 
                       asp-action="AddItemToShoppingCart"
                       asp-route-id="@item.Id"
                           title="Add to Cart" >➕</a>
                        <button class="overlay-btn" title="Like">❤️</button>
                    </div>
                    <div>
                        <a class="btn btn-success text-white @(DateTime.Now > item.EndDate ? "disabled" : "")"
                           style="width:100%; font-size:10px;"
                            asp-controller="Orders"
                            asp-action="AddItemToShoppingCart"
                            asp-route-id="@item.Id">
                            <i class="bi bi-cart-plus"></i> @item.Price.ToString("c")
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>


<script>
    document.querySelectorAll('.card-clickable').forEach(card => {
        card.style.cursor = 'pointer';
        card.addEventListener('click', function (e) {
            // لو المستخدم ضغط على زرار أو لينك جوا الكارد، ما يروحش لصفحة التفاصيل
            if (!e.target.closest('a') && !e.target.closest('button')&&!e.target.closest('span')) {
                window.location.href = card.getAttribute('data-href');
            }
        });
    });
</script>